/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author danie
 */
public class CadastroAnimal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroAnimal.class.getName());

    /**
     * Creates new form CadastroAnimal
     */
    public CadastroAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtCastrado = new javax.swing.JLabel();
        comboPorte = new javax.swing.JComboBox<>();
        txtPorte = new javax.swing.JLabel();
        comboFiv = new javax.swing.JComboBox<>();
        edtNome = new javax.swing.JTextField();
        txtNome = new javax.swing.JLabel();
        txtFiv = new javax.swing.JLabel();
        comboCor = new javax.swing.JComboBox<>();
        txtCor = new javax.swing.JLabel();
        comboGenero = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtGenero = new javax.swing.JLabel();
        comboRaca = new javax.swing.JComboBox<>();
        txtRaca = new javax.swing.JLabel();
        comboFelv = new javax.swing.JComboBox<>();
        comboDeficiencia = new javax.swing.JComboBox<>();
        txtFelv = new javax.swing.JLabel();
        txtTipo = new javax.swing.JLabel();
        comboPeso = new javax.swing.JComboBox<>();
        txtPeso = new javax.swing.JLabel();
        txtDeficiencia = new javax.swing.JLabel();
        txtPreferencias = new javax.swing.JLabel();
        comboCastrado = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnProx = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();
        comboIdade = new javax.swing.JComboBox<>();
        txtIdade = new javax.swing.JLabel();
        comboMicrochip = new javax.swing.JComboBox<>();
        txtMicrochip = new javax.swing.JLabel();
        painelCabecalho = new javax.swing.JPanel();
        btnNotificacao = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNomeUser = new javax.swing.JLabel();
        txtBemVindo = new javax.swing.JLabel();
        btnIcon = new javax.swing.JButton();
        txtFotoUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(232, 231, 204));

        jPanel3.setBackground(new java.awt.Color(232, 231, 204));

        txtCastrado.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtCastrado.setForeground(new java.awt.Color(0, 90, 81));
        txtCastrado.setText("Castrado");

        comboPorte.setForeground(new java.awt.Color(0, 90, 81));
        comboPorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPorte.addActionListener(this::comboPorteActionPerformed);

        txtPorte.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtPorte.setForeground(new java.awt.Color(0, 90, 81));
        txtPorte.setText("Porte");

        comboFiv.setForeground(new java.awt.Color(0, 90, 81));
        comboFiv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboFiv.addActionListener(this::comboFivActionPerformed);

        edtNome.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtNome.setForeground(new java.awt.Color(0, 90, 81));
        edtNome.setToolTipText("Infome o nome do animal");
        edtNome.setOpaque(false);
        edtNome.putClientProperty("Nimbus.Overrides", new javax.swing.UIDefaults());
        edtNome.setBorder(new javax.swing.border.AbstractBorder() {
            @Override
            public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new java.awt.Color(0, 90, 81)); 
                g2.drawRoundRect(x, y, width - 1, height - 1, 15, 15);
                g2.dispose();
            }
            @Override
            public java.awt.Insets getBorderInsets(java.awt.Component c) {
                return new java.awt.Insets(6, 12, 6, 12);
            }
        });
        edtNome.addActionListener(this::edtNomeActionPerformed);

        txtNome.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(0, 90, 81));
        txtNome.setText("Nome:");

        txtFiv.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtFiv.setForeground(new java.awt.Color(0, 90, 81));
        txtFiv.setText("Fiv");

        comboCor.setForeground(new java.awt.Color(0, 90, 81));
        comboCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCor.addActionListener(this::comboCorActionPerformed);

        txtCor.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtCor.setForeground(new java.awt.Color(0, 90, 81));
        txtCor.setText("Cor");

        comboGenero.setForeground(new java.awt.Color(0, 90, 81));
        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboGenero.addActionListener(this::comboGeneroActionPerformed);

        jComboBox1.setForeground(new java.awt.Color(0, 90, 81));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        txtGenero.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtGenero.setForeground(new java.awt.Color(0, 90, 81));
        txtGenero.setText("Genero");

        comboRaca.setForeground(new java.awt.Color(0, 90, 81));
        comboRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRaca.addActionListener(this::comboRacaActionPerformed);

        txtRaca.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtRaca.setForeground(new java.awt.Color(0, 90, 81));
        txtRaca.setText("Raça");

        comboFelv.setForeground(new java.awt.Color(0, 90, 81));
        comboFelv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboFelv.addActionListener(this::comboFelvActionPerformed);

        comboDeficiencia.setForeground(new java.awt.Color(0, 90, 81));
        comboDeficiencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDeficiencia.addActionListener(this::comboDeficienciaActionPerformed);

        txtFelv.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtFelv.setForeground(new java.awt.Color(0, 90, 81));
        txtFelv.setText("Felv");

        txtTipo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(0, 90, 81));
        txtTipo.setText("Tipo");

        comboPeso.setForeground(new java.awt.Color(0, 90, 81));
        comboPeso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPeso.addActionListener(this::comboPesoActionPerformed);

        txtPeso.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtPeso.setForeground(new java.awt.Color(0, 90, 81));
        txtPeso.setText("Peso");

        txtDeficiencia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtDeficiencia.setForeground(new java.awt.Color(0, 90, 81));
        txtDeficiencia.setText("Deficiência");

        txtPreferencias.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtPreferencias.setForeground(new java.awt.Color(0, 90, 81));
        txtPreferencias.setText("Informações complementares");

        comboCastrado.setForeground(new java.awt.Color(0, 90, 81));
        comboCastrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCastrado.addActionListener(this::comboCastradoActionPerformed);

        btnCancelar.setForeground(new java.awt.Color(0, 90, 81));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnProx.setBackground(new java.awt.Color(250, 166, 190));
        btnProx.setForeground(new java.awt.Color(0, 90, 81));
        btnProx.setText("Próximo");
        btnProx.setAutoscrolls(true);
        btnProx.addActionListener(this::btnProxActionPerformed);

        txtTitulo.setBackground(new java.awt.Color(232, 231, 204));
        txtTitulo.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 90, 81));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Cadastrar Animal");

        comboIdade.setForeground(new java.awt.Color(0, 90, 81));
        comboIdade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboIdade.addActionListener(this::comboIdadeActionPerformed);

        txtIdade.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtIdade.setForeground(new java.awt.Color(0, 90, 81));
        txtIdade.setText("Idade");

        comboMicrochip.setForeground(new java.awt.Color(0, 90, 81));
        comboMicrochip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMicrochip.addActionListener(this::comboMicrochipActionPerformed);

        txtMicrochip.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtMicrochip.setForeground(new java.awt.Color(0, 90, 81));
        txtMicrochip.setText("Raça");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNome)
                    .addComponent(txtPreferencias)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnProx))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipo)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCor)
                            .addComponent(comboIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGenero)
                            .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRaca)
                            .addComponent(comboMicrochip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMicrochip))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeficiencia)
                            .addComponent(comboCastrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCastrado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboPorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPorte))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboFiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFiv)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPeso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboFelv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFelv)))))
                    .addComponent(edtNome)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(txtPreferencias)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMicrochip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboMicrochip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtDeficiencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCastrado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboCastrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtPorte)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboPorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtFiv)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboFiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtPeso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtFelv)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboFelv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(50, 50, 50)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnProx))
                .addGap(140, 140, 140))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelCabecalho.setBackground(new java.awt.Color(0, 90, 81));
        painelCabecalho.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        painelCabecalho.setForeground(new java.awt.Color(0, 90, 81));
        painelCabecalho.setEnabled(false);

        btnNotificacao.setBackground(new java.awt.Color(0, 90, 81));
        btnNotificacao.setForeground(new java.awt.Color(0, 90, 81));
        btnNotificacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/notificacao.png"))); // NOI18N
        btnNotificacao.setBorder(null);
        btnNotificacao.addActionListener(this::btnNotificacaoActionPerformed);

        jPanel2.setBackground(new java.awt.Color(0, 90, 81));

        txtNomeUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNomeUser.setForeground(new java.awt.Color(250, 166, 190));
        txtNomeUser.setText("ADM     XXXX");
        txtNomeUser.setToolTipText("");
        txtNomeUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtBemVindo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtBemVindo.setForeground(new java.awt.Color(232, 231, 204));
        txtBemVindo.setText("Bem vindo!!");
        txtBemVindo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtNomeUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNomeUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBemVindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIcon.setBackground(new java.awt.Color(0, 90, 81));
        btnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_acolhepet.png"))); // NOI18N
        btnIcon.setBorder(null);
        btnIcon.addActionListener(this::btnIconActionPerformed);

        txtFotoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_user.png"))); // NOI18N

        javax.swing.GroupLayout painelCabecalhoLayout = new javax.swing.GroupLayout(painelCabecalho);
        painelCabecalho.setLayout(painelCabecalhoLayout);
        painelCabecalhoLayout.setHorizontalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFotoUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNotificacao)
                .addGap(24, 24, 24))
        );
        painelCabecalhoLayout.setVerticalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                .addGroup(painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFotoUser)
                        .addGroup(painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnNotificacao))
                            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotificacaoActionPerformed

    private void btnIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconActionPerformed

    private void comboPorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPorteActionPerformed

    private void comboFivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFivActionPerformed

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeActionPerformed

    private void comboCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCorActionPerformed

    private void comboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGeneroActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void comboRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRacaActionPerformed

    private void comboFelvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFelvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFelvActionPerformed

    private void comboDeficienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeficienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDeficienciaActionPerformed

    private void comboPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPesoActionPerformed

    private void comboCastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCastradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCastradoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProxActionPerformed

    private void comboIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIdadeActionPerformed

    private void comboMicrochipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMicrochipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMicrochipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroAnimal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIcon;
    private javax.swing.JButton btnNotificacao;
    private javax.swing.JButton btnProx;
    private javax.swing.JComboBox<String> comboCastrado;
    private javax.swing.JComboBox<String> comboCor;
    private javax.swing.JComboBox<String> comboDeficiencia;
    private javax.swing.JComboBox<String> comboFelv;
    private javax.swing.JComboBox<String> comboFiv;
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JComboBox<String> comboIdade;
    private javax.swing.JComboBox<String> comboMicrochip;
    private javax.swing.JComboBox<String> comboPeso;
    private javax.swing.JComboBox<String> comboPorte;
    private javax.swing.JComboBox<String> comboRaca;
    private javax.swing.JTextField edtNome;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel painelCabecalho;
    private javax.swing.JLabel txtBemVindo;
    private javax.swing.JLabel txtCastrado;
    private javax.swing.JLabel txtCor;
    private javax.swing.JLabel txtDeficiencia;
    private javax.swing.JLabel txtFelv;
    private javax.swing.JLabel txtFiv;
    private javax.swing.JLabel txtFotoUser;
    private javax.swing.JLabel txtGenero;
    private javax.swing.JLabel txtIdade;
    private javax.swing.JLabel txtMicrochip;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtNomeUser;
    private javax.swing.JLabel txtPeso;
    private javax.swing.JLabel txtPorte;
    private javax.swing.JLabel txtPreferencias;
    private javax.swing.JLabel txtRaca;
    private javax.swing.JLabel txtTipo;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
